/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:9bc683d9-2258-4230-9155-3289c83d1ea0",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_qrIW4uYmd",
    "aws_user_pools_web_client_id": "308lk03naovadll3qhb5b1mff2",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://mr644qwztfhhtl3sskpm6dmha4.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-pcsaql5e4nb7dclizyedb4gm3u",
    "aws_user_files_s3_bucket": "amplifyappimages191625-env",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
